### PR TITLE
canctl: fix coding style

### PR DESCRIPTION
**Pull request by marckleinebudde**

### CODE REVIEW

**Comment by jjorge-geotab** [comment]
My apologies. As I asked in #35, are you using the style checker from the kernel? I want to avoid these problems down the road.

**Comment by yegorich** [comment]
LGTM

**Comment by marckleinebudde** [comment]
I imported `.clang-format` in https://github.com/linux-can/socketcand/pull/46.

**Comment by jjorge-geotab** [comment]
> I imported `.clang-format` in #46.

Many thanks

**Pull request merged**
